import React from 'react'
import enzyme from 'enzyme'
import superagent from 'superagent'
import mocker from 'superagent-mocker'
import appStoreCreate from'../lib/app-store-create.js'
import SettingContainer from '../component/settings-container'
